# Percentage of account value to use
max_account_usable = 50
time_zone = "America/New_York"

#Path to the credentials file
credentials_filepath = "{home}/Documents/equitiestradingbot/test/test_data/credentials"

# Seconds to wait for between each spin of the bot across all markets
spin_interval = 3600

#Enable paper trading
paper_trading = false

[logging]
enable = true
log_filepath = "{home}/Documents/equitiestradingbot/log/trading_bot_{timestamp}.log"
debug = false 

[market_source]
active = "watchlist"
values = ['list", "api", "watchlist"]
[market_source.epic_id_list]
filepath = "{home}/Documents/equitiestradingbot/data/epic_ids.txt